<img src="figs/cit_hub_logo.png" alt="logo" width="300"/>

# Dictionaries and Frequency Tables

In this lesson we'll learn how to create dictionaries, index dictionaries, and understand key-value pairs.

We'll work with a [dataset that stores information for 7,197 mobile apps](https://www.kaggle.com/datasets/ramamet4/app-store-apple-data-set-10k-apps). Within this dataset, the `cont_rating` column offers information about the content rating of each app. The content rating of an app (also known as the maturity rating) represents the age required to use that app. The table below shows the unique content ratings in our dataset, along with the number of apps specific to each rating:

| Content rating | Number of apps |
| --- | --- | 
| 4+ | 4,433 |
| 9+ | 987 |
| 12+ | 1,155 |
| 17+ | 622 |

From the table above, we can see the following:

- Most apps (4,433) have a content rating of `4+` (only people aged four or older are recommended to use these apps).
- Apps with a content rating of `17+` are the fewest (622).
- In the middle, we have the `9+` and `12+` apps — 987 apps have a content rating of 9+, and 1,155 apps have a rating of 12+.

If we want to save the data from the table above, we can use two lists or a list of lists which we'll try in the following exercise. Next, we'll learn about dictionaries and explore a more efficient solution for storing the data above.

### Practice

1. Store the data in the table above using two different lists.
    - Assign the list `['4+', '9+', '12+', '17+']` to a variable named `content_ratings`. 
    - Assign the list `[4433, 987, 1155, 622]` to a variable named `numbers`.
    
    
2. Store the data in the table above using a list of lists. Assign the list `[['4+', '9+', '12+', '17+'], [4433, 987, 1155, 622]]` to a variable named `content_rating_numbers`.

In [2]:
# Two lists
content_ratings = ['4+', '9+', '12+', '17+']
numbers = [4433, 987, 1155, 622]

# A list of lists
content_rating_numbers = [['4+', '9+', '12+', '17+'],
                          [4433, 987, 1155, 622]]

print(content_rating_numbers)

[['4+', '9+', '12+', '17+'], [4433, 987, 1155, 622]]


Looking at the lists above, it may not be clear which content rating corresponds to which number — especially for someone without enough context. We need to find a better way to map a content rating to its corresponding number.

Each list element has an index number. Let's consider the `numbers` list:

![lists](figs/4-1-lists.svg)

What if we could transform the index numbers to content rating values? This way, the mapping between content ratings and their corresponding numbers would be much clearer

![lists](figs/4-2-lists.svg)

Fortunately, we can do this using a **dictionary**:

In [3]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
print(content_ratings)

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


To create the dictionary above, complete the following:

* Map each content rating to its corresponding number by following an `index:value` pattern. For instance, to map a rating of `'4+'` to the number `4,433`, we type `'4+': 4433` (notice the colon between `'4+'` and `4433`). To map `'9+'` to `987`, we type `'9+': 987`, and so on.


* Type the entire sequence of index:value pairs and separated each with a comma: `'4+': 4433, '9+': 987, '12+': 1155, '17+': 622`.


* Surround the sequence with curly braces: `{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}`


The animation below demonstrates the transition from table to dictionary.

![dict](figs/dict.gif)

Now, let's try to create the content_ratings dictionary ourselves.

### Practice

1. Map content ratings to their corresponding numbers by recreating the dictionary above: `{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}`. Assign the dictionary to a variable named `content_ratings`.


2. Print `content_ratings`, and examine the output carefully.

In [4]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
print(content_ratings)

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


Using a dictionary allows us to change the index numbers of a list to content rating values. That way, the mapping between content ratings and their corresponding numbers becomes clearer.

In [5]:
numbers = [4433, 987, 1155, 622]
# Index num 0     1     2    3

numbers = [4433, 987, 1155, 622]
# Index num  0    1     2    3

#          '4+'  '9+' '12+' '17+' 

content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
print(content_ratings)

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


To retrieve the individual values of the content_ratings dictionary, we can use the new indices. We retrieve individual dictionary values the same way we retrieve individual list elements — we follow a `variable_name[index]` pattern:

In [6]:
numbers = [4433, 987, 1155, 622]
print(numbers[0])
print(numbers[2])

4433
1155


In [7]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
print(content_ratings['4+'])
print(content_ratings['12+'])

4433
1155


### Practice

Now, let's practice retrieving a few dictionary values.

1. Retrieve values from the `content_ratings` dictionary.
    * Assign the value at index `'9+'` to a variable named `over_9`.
    * Assign the value at index `'17+'` to a variable named `over_17`.


2. Print `over_9` and `over_17`.

In [9]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

over_9 = content_ratings['9+']
over_17 = content_ratings['17+']

print(over_9)
print(over_17)

987
622


### Creating dictionaries

Alternatively to the way shown above, we can create a dictionary and populate it with values by following these steps:

1. Create an empty dictionary.


2. Add values one by one to that empty dictionary.


Adding a value to a dictionary follows the pattern `dictionary_name[index] = value`. To add a value `4433` with an index `'4+'` to a dictionary named `content_ratings`, we need to use the code `content_ratings['4+'] = 4433`

In [10]:
content_ratings = {} 
content_ratings['4+'] = 4433

print(content_ratings)

{'4+': 4433}


We can keep adding values using the same approach:

In [11]:
content_ratings = {} 
content_ratings['4+'] = 4433
content_ratings['9+'] = 987
content_ratings['12+'] = 1155
content_ratings['17+'] = 622

print(content_ratings)

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


This approach is the same as populating an empty list by using the `list_name.append()` command. The syntax is different, but fundamentally we take the same steps:

1. Create an empty dictionary (or list).


2. Add values using the `dictionary_name[index] = value` technique (or the `list_name.append()` command in case of a list).


Let us focus on practicing this new technique.

### Practice 

1. Use the new technique we learned to map content ratings to their corresponding numbers inside a dictionary.
    - Create an empty dictionary named `content_ratings`.
    - Add the `index:value` pairs one by one using the `dictionary_name[index] = value` technique. This should be the final form of the dictionary: `{'12+': 1155, '17+': 622, '4+': 4433, '9+': 987}`.
    
    
2. Retrieve the value at index `12+` from the `content_ratings` dictionary and assign it to a variable named `over_12_n_apps`.

In [12]:
content_ratings = {} 
content_ratings['4+'] = 4433
content_ratings['9+'] = 987
content_ratings['12+'] = 1155
content_ratings['17+'] = 622

over_12_n_apps = content_ratings['12+']
print(over_12_n_apps)

1155


## Keys and Values of a Dictionary

The index of a dictionary value is called a **key**. In `'4+': 4433`, the dictionary key is `'4+'`, and the dictionary **value** is `4433`. As a whole, '4+': 4433 is a **key-value pair.**

![lists](figs/4-3-dict.svg)

Dictionary values can be of any data type: `strings, integers, floats, Booleans, lists`, and even `dictionaries`.

In [13]:
d_1 = {'key_1': 'value_1', 
       'key_2': 1,
       'key_3': 1.832,
       'key_4': False,
       'key_5': [1,2,3],
       'key_6': {'inner_key' : 10}}

print(d_1)
print(d_1['key_1'])
print(d_1['key_6'])

{'key_1': 'value_1', 'key_2': 1, 'key_3': 1.832, 'key_4': False, 'key_5': [1, 2, 3], 'key_6': {'inner_key': 10}}
value_1
{'inner_key': 10}


Dictionary keys can be almost any data type, except lists and dictionaries. If we use lists or dictionaries as dictionary keys, we'll get an error:

In [14]:
d_1 = {5: 'int',
       '5': 'string',
       3.5: 'float',
       False: 'Boolean'}

print(d_1)

{5: 'int', '5': 'string', 3.5: 'float', False: 'Boolean'}


In [15]:
d_2 = {[1,2,3]: 'list'}

print(d_2)

TypeError: unhashable type: 'list'

## Populating a dictionary with data

When we populate a dictionary, Python tries to convert each dictionary key to an integer (even if the key is a data type other than an integer). Python does the conversion using the `hash()` command:

In [16]:
print(hash(4))
print(hash('four'))
print(hash(3.32))
print(hash(True))

4
-4683470947351128498
737869762948381699
1


For reasons we'll understand later, the `hash()` command doesn't transform lists and dictionaries to integers. It returns an error instead. Notice the error messages are the same as when we tried to use lists or dictionaries as keys.

In [17]:
print(hash([1,2,3]))

TypeError: unhashable type: 'list'

When we populate a dictionary, we also need to make sure each key in that dictionary is unique. If we use an identical key for two or more different values, Python keeps only the first key and the last value and removes the others — this means that we'll lose data. We illustrate this below:

In [18]:
d_1 = {'a_key': 1,
       'another_key': 2,
       'a_key': 3,
       'yet_another_key': 4,
       'a_key': 5}

print(d_1)

{'a_key': 5, 'another_key': 2, 'yet_another_key': 4}


An odd "gotcha" is when we mix integers with Booleans as dictionary keys. The `hash()` command converts the Boolean `True` to `1`, and the Boolean `False` to `0`. This means the Booleans `True` and `False` will conflict with the integers `0` and `1`. The dictionary keys won't be unique anymore, and Python will only keep the first key and the last value in cases like that.

In [19]:
d_1 = {1: 'one', True: 'Boolean'}
d_2 = {False: 'Bool', 0: 'zero'}
d_3 = {0: 'zero', 1: 'one',  2: 'two', True: 'true',
       False: 'false'}

print(d_1)
print(d_2)
print(d_3)

{1: 'Boolean'}
{False: 'zero'}
{0: 'false', 1: 'true', 2: 'two'}


## Summary

Congratulations. In this lesson, we learned how to create dictionaries, index dictionaries, and understand key-value pairs.