<img src="figs/cit_hub_logo.png" alt="logo" width="300"/>


# Dictionaries and Freqency Tables

In this lesson on dictionaries and frequency tables, we'll learn how to check for dictionary membership, update dictionary values, and count values using dictionaries.

Previously you may have worked with a small table showing the four unique content ratings in our dataset, along with the number of apps corresponding to each rating.


| Content rating | Number of apps |
| --- | --- | 
| 4+ | 4,433 |
| 9+ | 987 |
| 12+ | 1,155 |
| 17+ | 622 |

You may wonder how we manage to count the number of apps for each unique content rating. How did we find out there are `4,433` apps with a `4+` content rating, or `622` apps with a `17+` rating? Part of the answer is a technique that uses the special properties of dictionaries. The full answer is a bit lengthier: we'll learn how to count the number of apps for each unique content rating.

Once we've created a dictionary, we can check if a certain value exists in the dictionary as a key. We can check, for instance, if the value `'12+'` exists as a key in the dictionary `{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}`. To do that, we use the **`in`** operator.

In [1]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

print('12+' in content_ratings)

True


The `'12+'` in content_ratings expression returned the Boolean `True`, because the string `'12+'` exists in the dictionary `content_ratings` as a key.

If we use `in` with a certain value that doesn't exist among a dictionary's keys, we'll get `False`. For instance, checking if the string `'10+'` exists in the dictionary `content_ratings` returns `False` because there's no dictionary key `'10+'` in `content_ratings`.

In [2]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

print('10+' in content_ratings)
print('12+' in content_ratings)

False
True


Checking if `4433` or `987` exists in `content_ratings` also returns `False` because the search is only for the dictionary's keys (`4433` and `987` exist as dictionary values in `content_ratings`).

In [3]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

print(4433 in content_ratings)
print(987 in content_ratings)

False
False


An expression of the form `a_value in a_dictionary` always returns a Boolean value:

* We get `True` if `a_value` exists in `a_dictionary` as a dictionary key.

* We get `False` if `a_value` doesn't exist `in a_dictionary` as a dictionary key.

### Practice

Now let's practice using the in operator.

1. Using the `in` operator, check whether the following values exist as dictionary keys in the content_ratings dictionary:

    - The string `'9+'`- Assign the output of the expression to a variable named `is_in_dictionary_1`.
    - The integer `987`- Assign the output of the expression to a variable named `is_in_dictionary_2`.


2. Combine the output of an expression containing `in` with an `if` statement. If the string `'17+'` exists as dictionary key in `content_ratings`, then complete the following:

    - Assign the string "`It exists`" to a variable named `result`.
    - Print the result variable.

In [4]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

is_in_dictionary_1 = '9+' in content_ratings
is_in_dictionary_2 = 987 in content_ratings

if '17+' in content_ratings:
    result = "It exists"
    print(result)

# Alternative solution
is_in_dictionary = '17+' in content_ratings
if is_in_dictionary:
    result = "It exists"
    print(result)

It exists
It exists


## Updating a dictionary

Once we've created and populated a dictionary, we can update (change) the dictionary values. To update a dictionary value, we need to reference it by its corresponding dictionary key and then perform the updating operation we want. In the code example below, we do the following:

- Change the value corresponding to the dictionary key `'4+'` from `4433` to `0`.
- Add `13` to the value corresponding to the dictionary key `'9+'`.
- Subtract `1155` from the value corresponding to the dictionary key `'12+'`.
- Change the value corresponding to the dictionary key `'17+'` from `622` (`integer`) to '`622`' (`string`).

![dictionaries](figs/4-3-dict2.svg)

### Practice

The content_ratings dictionary is corrupt and needs to be fixed. The corrupt version of `content_ratings` is provided in the code editor.

1. Swap the values stored in the `4+` and `17+` keys.
    - Assign the value stored in `4+` to a temporary variable called `temp`.
    - Assign the value stored in `17+` to `4+`.
    - Assign the value stored in the temporary variable to `17+`.
    
    
2. Convert the value stored in `12+` into an integer.


3. Print the `content_ratings` dictionary.

In [5]:
content_ratings = {'4+': 622, '12+': '1155', '9+': 987, '17+': 4433}

temp = content_ratings['4+']
content_ratings['4+'] = content_ratings['17+']
content_ratings['17+'] = temp
content_ratings['12+'] = int(content_ratings['12+'])
print(content_ratings)

{'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}


We can update dictionary values to count how many times each unique content rating occurs in our dataset. Let's start by considering the list `['4+', '4+', '4+', '9+', '9+', '12+', '17+']`, which stores a few content ratings. To use code to count how many times each rating occurs in this short list, let's complete the following:

* Create a dictionary where the keys are the unique content ratings and the values are all `0`: `{'4+': 0, '9+': 0, '12+': 0, '17+': 0}`.

* Loop through the list `['4+', '4+', '4+', '9+', '9+', '12+', '17+']`, and for each iteration, do the following:
    * Check if the iteration variable exists as a key in the previously created dictionary.
    * If it exists, then increment the dictionary value at that key by `1`.

In [6]:
content_ratings = {'4+': 0, '9+': 0, '12+': 0, '17+': 0}
ratings = ['4+', '4+', '4+', '9+', '9+', '12+', '17+']

for c_rating in ratings:
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1

print(content_ratings)

{'4+': 3, '9+': 2, '12+': 1, '17+': 1}


To get a better understanding of how this works, we'll print the `content_rating` dictionary inside the for loop to see how it changes with every iteration, complete the following:

In [7]:
content_ratings = {'4+': 0, '9+': 0, '12+': 0, '17+': 0}
ratings = ['4+', '4+', '4+', '9+', '9+', '12+', '17+']

for c_rating in ratings:
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
    print(content_ratings)

print('Final dictionary:')
print(content_ratings)

{'4+': 1, '9+': 0, '12+': 0, '17+': 0}
{'4+': 2, '9+': 0, '12+': 0, '17+': 0}
{'4+': 3, '9+': 0, '12+': 0, '17+': 0}
{'4+': 3, '9+': 1, '12+': 0, '17+': 0}
{'4+': 3, '9+': 2, '12+': 0, '17+': 0}
{'4+': 3, '9+': 2, '12+': 1, '17+': 0}
{'4+': 3, '9+': 2, '12+': 1, '17+': 1}
Final dictionary:
{'4+': 3, '9+': 2, '12+': 1, '17+': 1}


Now let's read in our `AppleStore.csv` dataset and use the technique above to count the number of times each unique content rating occurs. We should arrive at the same numbers we've been using in the table:

| Content rating | Number of apps |
| --- | --- | 
| 4+ | 4,433 |
| 9+ | 987 |
| 12+ | 1,155 |
| 17+ | 622 |

### Practice

Count the number of times each unique content rating occurs in the dataset.

1. Create a dictionary named `content_ratings` where the keys are the unique content ratings and the values are all `0` (the values of `0` are temporary at this point, and they'll be updated).


2. Loop through the `apps_data` list of lists and make sure you don't include the header row. For each iteration of the loop, do the following:
    - Assign the content rating value to a variable named `c_rating`. The content rating is at index number `10` in each row.
    - Check if `c_rating` exists as a key in content_ratings. If it exists, then increment the dictionary value at that key by `1` (the key is equivalent to the value stored in `c_rating`).
    
    
3. Outside the loop, print `content_ratings` to check if the counting worked as expected.

In [8]:
opened_file = open('AppleStore.csv', encoding="utf-8")
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

content_ratings = {'4+': 0, '9+': 0, '12+': 0, '17+': 0}

for row in apps_data[1:]:
    c_rating = row[10]
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
        
print(content_ratings)

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


### What if we do not know the dictionary values beforehand? 

Previously, we created the dictionary `{'4+': 0, '9+': 0, '12+': 0, '17+': 0}` before we looped over the dataset to count the occurrence of each content rating. Unfortunately, this approach requires us to know the unique values we want to count beforehand.

If we don't know the unique content ratings, then we don't have enough information to create the dictionary `{'4+': 0, '9+': 0, '12+': 0, '17+': 0}`. We need a way to extract this information.

Our dataset has `7,197` rows and it's impractical to go over each row and to determine the unique content ratings. As a workaround, we can modify the logic of the code we used on the previous screen to find the unique values automatically.

Let's consider again the count we did for the list `['4+', '4+', '4+', '9+', '9+', '12+', '17+']`. To perform the count while finding the unique values automatically, we will do the following:

1. Create an empty dictionary named content_ratings.


2. Loop through the list `['4+', '4+', '4+', '9+', '9+', '12+', '17+']` and check for every iteration where the iteration variable (`c_rating`) exists as a key in content_ratings.
    - If it exists, then increment the dictionary value at that key by `1`.
    - Else (if it doesn't exist), create a new key-value pair in the `content_ratings` dictionary, where the dictionary key is the iteration variable (`c_rating`) and the dictionary value is `1`.
    

In [9]:
content_ratings = {}
ratings = ['4+', '4+', '4+', '9+', '9+', '12+', '17+']

for c_rating in ratings:
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
    else:
        content_ratings[c_rating] = 1

print(content_ratings)

{'4+': 3, '9+': 2, '12+': 1, '17+': 1}


You might wonder why we created each dictionary key with a dictionary value of `1` instead of `0`. When we encounter a content rating, we need to count it, whether it already exists as a dictionary key or not. When a rating that isn't yet in the dictionary comes in, we need to initialize it and count it. We need to initialize it with a value of `1` to mark the fact that this rating has already occurred once. If we initialized the dictionary key with a value of `0`, we'd succeed in initializing but fail at the counting.

For a clearer picture of what we did above, we'll print the `content_rating` dictionary inside the for loop to see how it changes with every iteration:

In [10]:
content_ratings = {}
ratings = ['4+', '4+', '4+', '9+', '9+', '12+', '17+']

for c_rating in ratings:
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
    else:
        content_ratings[c_rating] = 1
    print(content_ratings)

print('Final dictionary:')
print(content_ratings)

{'4+': 1}
{'4+': 2}
{'4+': 3}
{'4+': 3, '9+': 1}
{'4+': 3, '9+': 2}
{'4+': 3, '9+': 2, '12+': 1}
{'4+': 3, '9+': 2, '12+': 1, '17+': 1}
Final dictionary:
{'4+': 3, '9+': 2, '12+': 1, '17+': 1}


### Practice

Now let us try this technique on our dataset

Count the number of times each unique content rating occurs in the dataset while finding the unique values automatically.

1. Create an empty dictionary named `content_ratings`.


2. Loop through the `apps_data` list of lists (don't include the header row). For each iteration of the loop, complete the following:
    - Assign the content rating value to a variable named `c_rating`. The content rating is at index number `10`.
    - Check if `c_rating` exists as a key in content_ratings.
    - If it exists, then increment the dictionary value at that key by `1` (the key is equivalent to the value stored in `c_rating`).
    - Create a new key-value pair in the dictionary, where the dictionary key is `c_rating` and the dictionary value is `1`.


3. Outside the loop, print `content_ratings` to check if the counting worked as expected.

In [11]:
opened_file = open('AppleStore.csv', encoding="utf-8")
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

content_ratings = {}

for row in apps_data[1:]:
    c_rating = row[10]
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
    else:
        content_ratings[c_rating] = 1
        
print(content_ratings)

{'4+': 4433, '12+': 1155, '17+': 622, '9+': 987}


## Frequency tables

We also call the number of times a unique value occurs a frequency. For this reason, we call tables like the one below frequency tables.


| Content rating | Number of apps |
| --- | --- | 
| 4+ | 4,433 |
| 9+ | 987 |
| 12+ | 1,155 |
| 17+ | 622 |

`4+` occurs `4,433` times, so it has a frequency of `4,433`. `12+` has a frequency of `1,155`. `9+` has a frequency of `987`. `17+` has the lowest frequency: `622`.

When we're analyzing frequencies, we might want to answer questions about proportions and percentages:

- What proportion of apps have a content rating of `4+`?
- What percentage of apps have a content rating of `17+`?
- What percentage of apps can a 15-year-old download?

The proportion of apps with a content rating of `4+` quantifies the number of `4+` apps relative to the total number of apps. There are `4,433` apps with a content rating of `4+` and `7,197` apps in total, so the proportion of `4+` apps in our dataset is $\frac{4433}{7197}$.

Rather than using a fraction, it's more common to express the proportion as a decimal between `0` and `1`. So we'd say that that `0.62`  (the result of $\frac{4433}{7197}$, rounded to two decimal places) of the apps have a content rating of `4+`.

To get percentages, we only need to multiply the proportions by `100`. Since the proportion of `4+` is `0.62`, the percentage i is `62%`.

Next screen, we'll learn how to compute proportions and percentages using dictionaries. Let's practice what we've learned by creating a frequency table for the `prime_genre` column, which lists the genre for each app.

### Practice

**Instructions**

Count the number of times each unique genre occurs.

1. Create an empty dictionary named `genre_counting`.


2. Loop through the `apps_data` list of lists (don't include the header row). For each iteration of the loop, do the following:
    - Assign the genre to a variable named `genre`. The genre comes as a string and has the index number `11`.
    - Check if genre exists as a key in `genre_counting`.
    - If it exists, then increment the dictionary value at that key by `1` (the key is equivalent to the value stored in genre). 
    - Else, create a new key-value pair in the dictionary, where the dictionary key is genre and the dictionary value is `1`.


3. Outside the loop, print `genre_counting` and try to determine the most common app genre in our dataset.

In [12]:
opened_file = open('AppleStore.csv', encoding="utf-8")
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

genre_counting = {}

for row in apps_data[1:]:
    genre = row[11]    
    if genre in genre_counting:
        genre_counting[genre] += 1
    else:
        genre_counting[genre] = 1
        
print(genre_counting)

# The most common app genre is 'Games' (there are 3862 gaming apps)

{'Games': 3862, 'Productivity': 178, 'Weather': 72, 'Shopping': 122, 'Reference': 64, 'Finance': 104, 'Music': 138, 'Utilities': 248, 'Travel': 81, 'Social Networking': 167, 'Sports': 114, 'Business': 57, 'Health & Fitness': 180, 'Entertainment': 535, 'Photo & Video': 349, 'Navigation': 46, 'Education': 453, 'Lifestyle': 144, 'Food & Drink': 63, 'News': 75, 'Book': 112, 'Medical': 23, 'Catalogs': 10}


### Transforming frequency tables to proportions

To transform frequencies to proportions or percentages, we can update the dictionary values individually by performing the required arithmetical operations. Below, we divide each dictionary value by the total number of apps to go from frequencies to proportions.


In [13]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
total_number_of_apps = 7197

content_ratings['4+'] /= total_number_of_apps
content_ratings['9+'] /= total_number_of_apps
content_ratings['12+'] /= total_number_of_apps
content_ratings['17+'] /= total_number_of_apps

print(content_ratings)

{'4+': 0.6159510907322495, '9+': 0.13714047519799916, '12+': 0.16048353480616923, '17+': 0.08642489926358204}


Updating each individual dictionary value can become tedious as the dictionary length increases. For a dictionary with `20` key-value pairs, we'd have to manually update `20` dictionary values. Fortunately, we can speed up the process using a `for` loop.

When we iterate over a dictionary with a for loop, we loop over the dictionary keys by default:

In [14]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

for iteration_variable in content_ratings:
    print(iteration_variable)

4+
9+
12+
17+


We can use the dictionary keys to access the dictionary values within the loop:

In [15]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

for iteration_variable in content_ratings:
    print(iteration_variable)
    print(content_ratings[iteration_variable])

4+
4433
9+
987
12+
1155
17+
622


This allows us to update the dictionary values within the loop. This is how we could transform frequencies to proportions from within the loop:

In [16]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
total_number_of_apps = 7197

for iteration_variable in content_ratings:
    content_ratings[iteration_variable] /= total_number_of_apps

print(content_ratings)

{'4+': 0.6159510907322495, '9+': 0.13714047519799916, '12+': 0.16048353480616923, '17+': 0.08642489926358204}


### Practice

Let's practice this technique by doing a few exercises. Start by answering the two questions we left unanswered on the previous screen:

- What percentage of apps has a content rating of '`17+`'?
- What percentage of apps can a 15-year-old download?



In [17]:
content_ratings = {'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}
total_number_of_apps = 7197

for rating in content_ratings:
    content_ratings[rating] /= total_number_of_apps
    content_ratings[rating] *= 100
    
percentage_17_plus = content_ratings['17+']
percentage_15_allowed = content_ratings['4+'] + content_ratings['9+'] + content_ratings['12+']

print(percentage_17_plus)
print(percentage_15_allowed)

8.642489926358204
91.35751007364179


### Careful when updating the dictionary

Previously, we transformed frequencies to proportions or percentages by overwriting the initial dictionary values. However, we'll often need to keep the dictionaries separate for later analysis. For instance, we might want to have three separate dictionaries: one for storing frequencies, one for storing proportions, and another for storing percentages.

When we transform frequencies to proportions, we can create a new dictionary instead of overwriting the values in the initial dictionary. To do that, we can create a new empty dictionary and populate it within the loop:


In [18]:
content_ratings = {'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}
total_number_of_apps = 7197
c_ratings_proportions = {}

for key in content_ratings:
    proportion = (content_ratings[key] / total_number_of_apps)     
    c_ratings_proportions[key] = proportion

print(c_ratings_proportions)
print(content_ratings)

{'4+': 0.6159510907322495, '12+': 0.16048353480616923, '9+': 0.13714047519799916, '17+': 0.08642489926358204}
{'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}


To see how this works, we'll print the iteration variable, the proportion, and the new dictionary for every iteration:

In [19]:
content_ratings = {'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}
total_number_of_apps = 7197
c_ratings_proportions = {}

for key in content_ratings:
    proportion = (content_ratings[key] / total_number_of_apps)     
    print('Key:', key)
    print('Proportion value:', proportion)

    c_ratings_proportions[key] = proportion
    print(c_ratings_proportions)

Key: 4+
Proportion value: 0.6159510907322495
{'4+': 0.6159510907322495}
Key: 12+
Proportion value: 0.16048353480616923
{'4+': 0.6159510907322495, '12+': 0.16048353480616923}
Key: 9+
Proportion value: 0.13714047519799916
{'4+': 0.6159510907322495, '12+': 0.16048353480616923, '9+': 0.13714047519799916}
Key: 17+
Proportion value: 0.08642489926358204
{'4+': 0.6159510907322495, '12+': 0.16048353480616923, '9+': 0.13714047519799916, '17+': 0.08642489926358204}


### Practice

Now, let us practice this technique. 

Transform the frequencies inside `content_ratings` to proportions and percentages while creating separate dictionaries for each.

- Assign the dictionary storing proportions to a variable named `c_ratings_proportions`.
- Assign the dictionary storing percentages to a variable named `c_ratings_percentages`.

Optional challenge: try to solve this exercise using a single for loop.

In [20]:
content_ratings = {'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}
total_number_of_apps = 7197

c_ratings_proportions = {}
for key in content_ratings:
    proportion = content_ratings[key] / total_number_of_apps    
    c_ratings_proportions[key] = proportion

c_ratings_percentages = {}
for key in c_ratings_proportions:
    percentage = c_ratings_proportions[key] * 100
    c_ratings_percentages[key] = percentage
    
'''
*** Solution to the challenge ***

c_ratings_proportions = {}
c_ratings_percentages = {}

for key in content_ratings:
    proportion = content_ratings[key] / total_number_of_apps
    percentage = proportion * 100
    
    c_ratings_proportions[key] = proportion
    c_ratings_percentages[key] = percentage
'''

'\n*** Solution to the challenge ***\n\nc_ratings_proportions = {}\nc_ratings_percentages = {}\n\nfor key in content_ratings:\n    proportion = content_ratings[key] / total_number_of_apps\n    percentage = proportion * 100\n    \n    c_ratings_proportions[key] = proportion\n    c_ratings_percentages[key] = percentage\n'

### Choose carefully how to create frequency tables

Creating frequency tables for certain columns may result in lengthy dictionaries due to the large number of unique values. For example, consider the `size_bytes` column (the third column in the table below), which describes the data size of an app.

Below, we generate a frequency table for the `size_bytes` column. We see there are `7,107` key-value pairs in the resulting dictionary.

In [21]:
size_freq = {}

for row in apps_data[1:]:
    size = row[2]

    if size in size_freq:
        size_freq[size] +=1
    else:
        size_freq[size] = 1

print(len(size_freq))
print(size_freq)

7107
{'100788224': 1, '158578688': 1, '100524032': 1, '128512000': 1, '92774400': 1, '10485713': 1, '227795968': 1, '130242560': 1, '49250304': 1, '70023168': 1, '49618944': 1, '227547136': 1, '179979264': 1, '160925696': 1, '55153664': 1, '207907840': 1, '389879808': 1, '167407616': 1, '147093504': 1, '10735026': 1, '70707916': 1, '6169600': 1, '130583552': 1, '71203840': 1, '11423008': 1, '188017664': 1, '4765696': 1, '287933440': 1, '4263936': 1, '172772352': 1, '273844224': 1, '40216576': 1, '2386944': 1, '105431040': 1, '44129280': 1, '116443136': 2, '1646592': 1, '30016512': 1, '29518848': 1, '66872320': 1, '45229056': 1, '127470592': 1, '44241920': 1, '107983872': 1, '8044544': 1, '37214208': 1, '60320768': 1, '100849664': 1, '72748032': 1, '32164864': 1, '69079040': 1, '82037760': 1, '150195200': 1, '199734272': 1, '13156352': 1, '30367744': 1, '93420544': 1, '31505408': 1, '25997312': 1, '182054912': 1, '138754048': 1, '13564835': 1, '133688320': 1, '55205888': 1, '46922752': 

A long frequency table is difficult to analyze. The longer the table, the more difficult it becomes to identify patterns. As a workaround, we can create well-defined intervals and count the frequency for those intervals instead. For instance, we may want to create five intervals for the `size_bytes` column, and then count the number of apps specific to each interval.

| Data size (bytes) | Frequency |
| --- | --- | 
| 0 - 10,000,000 (0 - 10 MB) | 285|
| 10,000,000 - 50,000,000 (10 - 50 MB) | 1639|
| 50,000,000 - 100,000,000 (50 - 100 MB) | 1778|
| 100,000,000 - 500,000,000 (100 - 500 MB) | 2894|
| 500,000,000+ (500+ MB) | 601|

Using intervals helps us segment the data into groups, which makes analysis easier. Looking at the table above, we can see that most apps are between 100 and 500 MB, the fewest apps are under 10 MB, etc.

Choosing intervals isn't always straightforward. Above, we chose the intervals mostly based on our knowledge of common data sizes for phone apps. If we didn't have this information, we'd have to rely on something else to determine sensible intervals.

When we're trying to come up with some reasonable intervals, it often helps to know the minimum and the maximum values of a column. This helps us determine where the intervals should start and where they should end.

To determine the minimum and the maximum values of a column, we can use the `min()` and the `max()` commands. These two commands find out the minimum and the maximum values for any list of integers or floats.

In [22]:
a_list = [1, 20, 10.5, 4, 0]

print(max(a_list))
print(min(a_list))

20
0


In [23]:
# min() and max() do not work properly for strings
a_list = ['1', '20', '10.5', '4', '0']

print(max(a_list))
print(min(a_list))

4
0


To determine the minimum and maximum app data size, we need to extract the values in the `size_bytes` column as `floats` or integers in a separate list, and then use the `min()` and the `max()` commands on that list.

### Practice

1. Extract the values in the `size_bytes` column in a separate list.

    - Create an empty list named `data_sizes`.
    - Loop through `apps_data` (don't include the header row) and for every iteration, do the following:
        - Store the data size as a `float` in a variable named `size` (the index number for the data size is `2`).
        - Append `size` to the `data_sizes` list.
        
        
2. Determine the minimum and the maximum app data size.

    - Assign the minimum value to a variable named `min_size`.
    - Assign the maximum value to a variable named `max_size`.

In [26]:
opened_file = open('AppleStore.csv', encoding="utf-8")
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

data_sizes = []
for row in apps_data[1:]:
    size = float(row[2])
    data_sizes.append(size)
    
min_size = min(data_sizes)
max_size = max(data_sizes)

print(min_size)
print(max_size)

589824.0
4025969664.0


### Building a frequency table for our dataset

Based on the values we found in the previous exercise, let's use these intervals for the `size_bytes` column (note that the minimum and maximum values only informed our choice — they don't necessarily have to be the starting and ending point of the intervals):


| Data size (bytes) | Frequency |
| --- | --- | 
| 0 - 10,000,000 (0 - 10 MB) | 285|
| 10,000,000 - 50,000,000 (10 - 50 MB) | 1639|
| 50,000,000 - 100,000,000 (50 - 100 MB) | 1778|
| 100,000,000 - 500,000,000 (100 - 500 MB) | 2894|
| 500,000,000+ (500+ MB) | 601|

Once we know the intervals we want, we can continue computing the frequency for each interval.

| Data size (bytes) | Frequency |
| --- | --- | 
| 0 - 10,000,000 (0 - 10 MB) | ? |
| 10,000,000 - 50,000,000 (10 - 50 MB) | ? |
| 50,000,000 - 100,000,000 (50 - 100 MB) | ? |
| 100,000,000 - 500,000,000 (100 - 500 MB) | ? |
| 500,000,000+ (500+ MB) | ? |

We want to store the frequency table as a dictionary. We begin by creating a dictionary with the intervals as dictionary keys and frequencies as dictionary values (we initialize all frequencies with zero):


In [27]:
data_sizes = {'0 - 10 MB': 0, '10 - 50 MB': 0, '50 - 100 MB': 0,
                    '100 - 500 MB': 0, '500 MB +': 0}

Next, we loop through our dataset. For each iteration, do the following:

 - Store the data size as a `float` in a variable named `data_size`.
 - Determine which interval the data size belongs to by using an `if` statement followed by a series of `elif` clauses (we use `elif` to avoid redundant computations).
     - Increment the frequency in our dictionary by `1` depending on the interval to which the data size belongs.
     - Note that we use code like `10000000 < data_size <= 50000000` — this is equivalent to `10000000 < data_size and data_size <= 50000000`.

In [28]:
data_sizes = {'0 - 10 MB': 0, '10 - 50 MB': 0, '50 - 100 MB': 0,
                    '100 - 500 MB': 0, '500 MB +': 0}

for row in apps_data[1:]:
    data_size = float(row[2])

    if data_size <= 10000000:
        data_sizes['0 - 10 MB'] += 1

    elif 10000000 < data_size <= 50000000:
        data_sizes['10 - 50 MB'] += 1

    elif 50000000 < data_size <= 100000000:
        data_sizes['50 - 100 MB'] += 1

    elif 100000000 < data_size <= 500000000:
        data_sizes['100 - 500 MB'] += 1

    elif data_size > 500000000:
        data_sizes['500 MB +'] += 1


print(data_sizes)

{'0 - 10 MB': 285, '10 - 50 MB': 1639, '50 - 100 MB': 1778, '100 - 500 MB': 2894, '500 MB +': 601}


### Practice

Now let's practice this technique by creating a frequency table for the `rating_count_tot` column, which describes the total number of user ratings an app has received.


1. Find the minimum and maximum value in the `rating_count_tot` column.

    - Extract the values in the `rating_count_tot` column (index number `5`) in a separate list (convert to `integer` or `float`).
    - Determine the minimum and maximum value of that list using the `min()` and the `max()` commands.


2. Choose a few intervals (try to choose five intervals or fewer), based on the minimum and maximum value you've found.


3. Once you've chosen the intervals, compute the frequency of the apps for each interval. Store the frequency table in a dictionary.

    - Create a dictionary with intervals as dictionary keys and zeros as dictionary values.
    - Loop through the `apps_data` data set. Count the frequency of each interval using an `if` statement followed by a series of `elif` clauses.


4. Inspect the frequency table and analyze the results.

In [30]:
opened_file = open('AppleStore.csv', encoding="utf-8")
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

n_user_ratings = []
for row in apps_data[1:]:
    n_user_ratings.append(int(row[5]))
    
ratings_max = max(n_user_ratings)
ratings_min = min(n_user_ratings)

user_ratings_freq = {'0 - 10000': 0, '10000 - 100000': 0, '100000 - 500000': 0,
                    '500000 - 1000000': 0, '1000000+': 0}

for row in apps_data[1:]:
    user_ratings = int(row[5])
    
    if user_ratings <= 10000:
        user_ratings_freq['0 - 10000'] += 1
        
    elif 10000 < user_ratings <= 100000:
        user_ratings_freq['10000 - 100000'] += 1
        
    elif 100000 < user_ratings <= 500000:
        user_ratings_freq['100000 - 500000'] += 1
        
    elif 500000 < user_ratings <= 1000000:
        user_ratings_freq['500000 - 1000000'] += 1
        
    elif user_ratings > 1000000:
        user_ratings_freq['1000000+'] += 1


print(user_ratings_freq)

{'0 - 10000': 6181, '10000 - 100000': 798, '100000 - 500000': 196, '500000 - 1000000': 16, '1000000+': 6}


## Summary

Congratulations! In this lesson, we learned about dictionaries and how to use them to build frequency tables. Frequency tables are common in many computer fields. 